image: pjcuadra/sphinx-doc

stages:
  - build

pages:
  stage: build
  script:
  - curl -sLO https://github.com/github/git-lfs/releases/download/v2.0.1/git-lfs-linux-amd64-2.0.1.tar.gz
  - tar xf git-lfs-linux-amd64-2.0.1.tar.gz && mv git-lfs-2.0.1/git-lfs /usr/bin/ && rm -Rf git-lfs-2.0.1
  - pip install -r docs/dev/requirements.txt
  - git lfs pull
  - cd docs/dev && make html && cd ..
  - mv docs/dev/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

